name: flutter_weather
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ^3.29.0

dependencies:
  cached_network_image: ^3.4.1
  clock: ^1.1.2
  cloud_firestore: ^5.6.4
  collection: ^1.19.1
  data:
    path: packages/data
  domain:
    path: packages/domain
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  intl: ^0.20.2
  path: ^1.9.1
  provider: ^6.1.2
  share_plus: ^10.1.4

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  assets:
    - .env
