name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_tests_and_lint:
    name: Check Tests & Lint
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Check out repository
        uses: actions/checkout@v3

      # 2) Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"

      - name: Flutter Doctor
        run: flutter doctor -v

      # ---------------------------
      # ROOT: Format, Analyze, Test
      # ---------------------------
      - name: Install Dependencies (root)
        run: flutter pub get

      - name: Format (root)
        run: flutter format --set-exit-if-changed .

      - name: Analyze (root)
        run: flutter analyze

      - name: Test (root)
        run: flutter test --coverage

      # ------------------------------------
      # PACKAGES/DATA: Format, Analyze, Test
      # ------------------------------------
      - name: Install Dependencies (packages/data)
        run: |
          cd packages/data
          flutter pub get

      - name: Format (packages/data)
        run: |
          cd packages/data
          flutter format --set-exit-if-changed .

      - name: Analyze (packages/data)
        run: |
          cd packages/data
          flutter analyze

      - name: Test (packages/data)
        run: |
          cd packages/data
          flutter test --coverage

      # --------------------------------------
      # PACKAGES/DOMAIN: Format, Analyze, Test
      # --------------------------------------
      - name: Install Dependencies (packages/domain)
        run: |
          cd packages/domain
          flutter pub get

      - name: Format (packages/domain)
        run: |
          cd packages/domain
          flutter format --set-exit-if-changed .

      - name: Analyze (packages/domain)
        run: |
          cd packages/domain
          flutter analyze

      - name: Test (packages/domain)
        run: |
          cd packages/domain
          flutter test --coverage

  build_all_platforms:
    name: Build App (All Platforms)
    runs-on: macos-latest
    needs: check_tests_and_lint # Only run if tests & lint pass

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Dependencies (root)
        run: flutter pub get

      - name: Build Android
        run: flutter build apk --release

      - name: Build iOS
        run: flutter build ios --no-codesign

      - name: Build Web
        run: flutter build web

      - name: Build macOS
        run: flutter build macos --no-codesign
